import React from "react"

function Mentorship() {
  const undergraduateStudents = [
    {
      id: 26,
      student1: "Ishu Dhariwal (2K18/SE/068)",
      student2: "Bharat Lal (2K18/SE/045)",
      projectTitle:
        "A Nature-Influenced Gravitation Based Method for Link Prediction in Complex Network Systems",
      year: "2021-2022",
      paperPresented: "-",
    },
    {
      id: 25,
      student1: "Hardik Jain (2K18/SE/063)",
      student2: "Piyush Gupta (2K18/SE/093)",
      projectTitle: "An Advanced Study On Image Captioning Models",
      year: "2021-2022",
      paperPresented: "-",
    },
    {
      id: 24,
      student1: "Vivek Rajbhar (2K18/SE/134)",
      student2: "Vivek Shankerwal (2K18/SE/135)",
      projectTitle:
        "Traffic Sign Classification Using CNN, SVM, KNN and Random Forest",
      year: "2021-2022",
      paperPresented: "-",
    },
    {
      id: 23,
      student1: "Ajay Kumar (2K18/SE/014)",
      student2: "Akash (2K18/SE/015)",
      projectTitle:
        "Fake News Detection Using Different Machine Learning Algorithms",
      year: "2021-2022",
      paperPresented: "-",
    },
    {
      id: 22,
      student1: "Mayand Kumar (2K18/SE/078)",
      student2: "Aman Bhatia (2K18/SE/019)",
      projectTitle:
        "A Comparative Analysis of Deep Learning Algorithms for Skin Cancer Detection",
      year: "2021-2022",
      paperPresented: "-",
    },
    {
      id: 21,
      student1: "Dhruba Dutta (2K19/SE/37)",
      student2: "Harsh Prakash (2K19/SE/047)",
      projectTitle:
        "Skin Cancer Prediction with Edge Devices using YOLOv7 Deep Convolutional Neural Networks",
      year: "2022-23",
      paperPresented: "ICDAM",
    },
    {
      id: 20,
      student1: "Shah Faizal Khan (2K19/SE/112)",
      student2: "Sahil Kumar (2K19/SE/090)",
      projectTitle: "Comparative Study of Different Models of Image Captioning",
      year: "2022-23",
      paperPresented: "ICRTETBM",
    },
    {
      id: 19,
      student1: "Swayam Gupta (2K19/SE/131)",
      student2: "Vasu Gupta (2K19/SE/144)",
      projectTitle:
        "Multi-Objective Optimization on Gradient Boosting for Breast Cancer Prediction",
      year: "2022-23",
      paperPresented: "IJSAEM",
    },
    {
      id: 18,
      student1: "Farhan Raja (2K19/SE/41)",
      student2: "Hariom Sharma (2K19/SE/045)",
      projectTitle: "A Comparative Analysis of Hindi Image Captioning",
      year: "2022-23",
      paperPresented: "ICRTETBM",
    },
    {
      id: 17,
      student1: "Deng Daniel Ayuen Kur (2K19/SE/034)",
      student2: "NA",
      projectTitle:
        "A Comprehensive Comparison of Machine Learning Algorithms for Used Car Price Prediction",
      year: "2022-23",
      paperPresented: "-",
    },
    {
      id: 16,
      student1: "Prince (2K19/SE/086)",
      student2: "Sahil Kumar (2K19/SE/105)",
      projectTitle:
        "Sentiment Analysis of Captions Generated by Image Captioning Using Deep Learning",
      year: "2022-23",
      paperPresented: "ICDIS",
    },
    {
      id: 15,
      student1: "(Name Missing) (2K19/SE/030)",
      student2: "(Name Missing) (2K19/SE/026)",
      projectTitle: "Next-LSTM: A Novel LSTM-Based Image Captioning Technique",
      year: "2022-23",
      paperPresented: "IJSAEM",
    },
    {
      id: 14,
      student1: "Suryodaya Bikram Shahi (2K19/SE/154)",
      student2: "Shuvam Shiwakoti (2K19/SE/124)",
      projectTitle: "IoT-Based Control Networks and Intelligent Systems",
      year: "2022-23",
      paperPresented: "ICICNIS",
    },
    {
      id: 13,
      student1: "Aviral Tiwari (2K19/SE/024)",
      student2: "Asif Khan (2K19/SE/023)",
      projectTitle:
        "Human Emotion Detection Using Facial Expression and Voice Recognition",
      year: "2022-23",
      paperPresented: "ICRTETBM",
    },
    {
      id: 12,
      student1: "Riya Bansal (2K19/SE/01)",
      student2: "Chehak Agrawal (2K19/SE/031)",
      projectTitle:
        "Performance Analysis of Image Caption Generation Techniques using CNN-Based Encoder-Decoder Architecture",
      year: "2022-23",
      paperPresented: "ICDSNE 2023",
    },
    {
      id: 11,
      student1: "Ashutosh Thakur (2K19/SE/022)",
      student2: "Bhavishya (2K19/SE/028)",
      projectTitle:
        "A Novel Deep Learning-Based Fully Automated Framework for Captcha Security Vulnerability Checking",
      year: "2022-23",
      paperPresented: "ICDSNE 2023",
    },
    {
      id: 10,
      student1: "Prince Kumar (2K20/SE/100)",
      student2: "Ritik Panchal (2K20/SE/107)",
      projectTitle: "Comparing Breast Cancer Prediction Models",
      year: "2023-2024",
      paperPresented: "-",
    },
    {
      id: 9,
      student1: "Ekansh (2K20/SE/47)",
      student2: "Madhav Khattar (2K20/SE/78)",
      projectTitle:
        "Enhancing Tor-NonTor Traffic Classification Across Diverse Classifiers",
      year: "2023-2024",
      paperPresented: "ICICCT 2024",
    },
    {
      id: 8,
      student1: "Anamika (2K20/SE/015)",
      student2: "Khushi Singh (2K20/SE/74)",
      projectTitle:
        "Enhanced Image Captioning Using Scene Text - A Holistic Survey",
      year: "2023-2024",
      paperPresented: "ICMLBDA 2024",
    },
    {
      id: 7,
      student1: "Kartik Bisht (2K20/SE/69)",
      student2: "Kartik Bansal (2K20/SE/68)",
      projectTitle: "Wind Power Forecasting: A Novel Hybrid Approach",
      year: "2023-2024",
      paperPresented: "IJSAEM",
    },
    {
      id: 6,
      student1: "Pawan (2K20/SE/094)",
      student2: "NA",
      projectTitle: "Skin Cancer Prediction - A Comparative Review",
      year: "2023-2024",
      paperPresented: "-",
    },
    {
      id: 5,
      student1: "Pranav Singh Rathore (2K20/SE/98)",
      student2: "NA",
      projectTitle: "Change in Maintenance Strategy for Effective Maintenance",
      year: "2023-2024",
      paperPresented: "CCIT 2024",
    },
    {
      id: 4,
      student1: "Nikita (2K20/SE/91)",
      student2: "Ishanki Saxena (2K20/SE/61)",
      projectTitle:
        "Exploring the Effectiveness of BERT for Text Summarization",
      year: "2023-2024",
      paperPresented: "ICPEICES 2024",
    },
    {
      id: 3,
      student1: "Vaibhavi Sakhuja (2K20/SE/152)",
      student2: "Bhavil Ahuja (2K20/SE/42)",
      projectTitle:
        "Enhancing Image Captioning Using Ensemble Learning and CLIP Model",
      year: "2023-2024",
      paperPresented: "ICDAM 2024",
    },
    {
      id: 2,
      student1: "Sharda Nand Jha (2K20/SE/125)",
      student2: "Pranav Kumar Parihar (2K20/SE/097)",
      projectTitle: "Patient Categorization Using Drug Reviews",
      year: "2023-2024",
      paperPresented: "-",
    },
    {
      id: 1,
      student1: "Ayush Jaiswal (2K20/SE/36)",
      student2: "Bhavesh Baseshankar (2K20/SE/41)",
      projectTitle: "Skin Cancer Detection Using Deep Learning Models",
      year: "2023-2024",
      paperPresented: "-",
    },
  ]

  const postgraduateStudents = [
    {
      id: 6,
      name: "Ashish Verma",
      rollNo: "2K21/DSC/03",
      projectTitle:
        "An improved technique for effective image caption generation",
      year: "2022-23",
    },
    {
      id: 5,
      name: "Rishabh Sirohi",
      rollNo: "2K21/SWE/19",
      projectTitle:
        "An efficient machine learning tool for automatic bug triaging",
      year: "2022-23",
    },
    {
      id: 4,
      name: "Saransh Sharma",
      rollNo: "2K21/SWE/22",
      projectTitle:
        "Automatic comment generation using deep learning techniques",
      year: "2022-23",
    },
    {
      id: 3,
      name: "Div Chaudhary",
      rollNo: "2K22/SWE/05",
      projectTitle:
        "Impact of Context-based Word Embedding Techniques on Software Defect Prediction",
      year: "2023-2024",
    },
    {
      id: 2,
      name: "Abhishek Yadav",
      rollNo: "2K22/SWE/01",
      projectTitle:
        "Application of Sequential Models in Software Defect Prediction",
      year: "2023-2024",
    },
    {
      id: 1,
      name: "Gaurav Sharma",
      rollNo: "2K22/DSC/05",
      projectTitle:
        "Comparative Analysis of Word Embedding Techniques in Software Defect Prediction",
      year: "2023-2024",
    },
  ]

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 py-16">
      <div className="container mx-auto px-4">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold text-center mb-2">
            Mentorship
          </h1>
          <p className="text-gray-600 text-center mb-12 text-lg">
            Students guided by Priya Singh 
          </p>

          {/* Undergraduate Students Section */}
          <section className="mb-16">
            <h2 className="text-2xl md:text-3xl font-semibold text-gray-800 mb-6">
              Undergraduate Students
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-blue-600 text-white">
                    <th className="py-3 px-4 text-sm font-medium">S.No.</th>
                    <th className="py-3 px-4 text-sm font-medium">Student 1</th>
                    <th className="py-3 px-4 text-sm font-medium">Student 2</th>
                    <th className="py-3 px-4 text-sm font-medium">
                      Project Title
                    </th>
                    <th className="py-3 px-4 text-sm font-medium">Year</th>
                    <th className="py-3 px-4 text-sm font-medium">
                      Paper Presented
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {undergraduateStudents.reverse().map((student, index) => (
                    <tr
                      key={student.id}
                      className={`${
                        index % 2 === 0 ? "bg-white" : "bg-gray-50"
                      } hover:bg-gray-100 transition-colors`}
                    >
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.id}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.student1}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.student2}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.projectTitle}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.year}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.paperPresented}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Postgraduate Students Section */}
          <section className="mb-16">
            <h2 className="text-2xl md:text-3xl font-semibold text-gray-800 mb-6">
              Postgraduate Students
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-blue-600 text-white">
                    <th className="py-3 px-4 text-sm font-medium">S.No.</th>
                    <th className="py-3 px-4 text-sm font-medium">Name</th>
                    <th className="py-3 px-4 text-sm font-medium">Roll No.</th>
                    <th className="py-3 px-4 text-sm font-medium">
                      Project Title
                    </th>
                    <th className="py-3 px-4 text-sm font-medium">Year</th>
                  </tr>
                </thead>
                <tbody>
                  {postgraduateStudents.reverse().map((student, index) => (
                    <tr
                      key={student.id}
                      className={`${
                        index % 2 === 0 ? "bg-white" : "bg-gray-50"
                      } hover:bg-gray-100 transition-colors`}
                    >
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.id}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.name}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.rollNo}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.projectTitle}
                      </td>
                      <td className="py-3 px-4 text-sm text-gray-700">
                        {student.year}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}

export default Mentorship
